"use strict";
let lName;
lName = "Souza";
let newName = lName.toUpperCase();
console.log(newName);
let age;
age = 25;
age = 25.5;
let dob = "25";
let result = parseInt(dob);
let isValid = false;
console.log(isValid);
let empList;
empList = ["Souza", "Souza1", "Souza2"];
let numList;
numList = [1, 2, 3, 4, 5];
let results = numList.filter((num) => num > 2);
let num = numList.find((num) => num === 2);
console.log(results);
console.log(num);
// lname = 10;
